paths:
  /products:
    get:
      summary: Obtener todos los productos
      description: Retorna una lista de todos los productos o un número limitado de ellos
      tags:
        - productos
      produces:
        - application/json
      responses:
        200:
          description: Lista de productos obtenida con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        400:
          description: Error en la solicitud
        500:
          description: Se produjo un error en el servidor

    post:
      summary: Añadir un nuevo producto
      description: Permite a los usuarios administradores añadir un nuevo producto
      tags:
        - productos
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: Producto añadido con éxito
        400:
          description: Error al añadir el producto
        500:
          description: Se produjo un error en el servidor

  /products/{pid}:
    get:
      summary: Obtener un producto específico
      description: Retorna información detallada de un producto específico por ID
      tags:
        - productos
      parameters:
        - name: pid
          in: path
          required: true
          type: string
          description: ID del producto
      produces:
        - application/json
      responses:
        200:
          description: Información del producto obtenida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Producto no encontrado
        500:
          description: Se produjo un error en el servidor

    put:
      summary: Actualizar un producto específico
      description: Permite a los usuarios administradores actualizar la información de un producto específico
      tags:
        - productos
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: pid
          in: path
          required: true
          type: string
          description: ID del producto a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: Producto actualizado con éxito
        400:
          description: Error en la actualización del producto
        500:
          description: Se produjo un error en el servidor

    delete:
      summary: Eliminar un producto específico
      description: Permite a los usuarios administradores eliminar un producto específico
      tags:
        - productos
      produces:
        - application/json
      parameters:
        - name: pid
          in: path
          required: true
          type: string
          description: ID del producto a eliminar
      responses:
        200:
          description: Producto eliminado con éxito
        400:
          description: Error al eliminar el producto
        500:
          description: Se produjo un error en el servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto generado por MongoDB
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        code:
          type: string
          description: Código único del producto
        stock:
          type: number
          description: Stock del producto
        category:
          type: string
          description: Categoría del producto
        thumbnails:
          type: string
          description: Imágenes miniatura del producto
        status:
          type: boolean
          description: Estado de disponibilidad del producto
      example:
        _id: "5f50c31f1c9d44000047b039"
        title: "Manzanas"
        description: "Manzanas rojas y frescas"
        price: 3.5
        code: "APL123"
        stock: 50
        category: "Frutas y verduras"
